term.clear()
term.setCursorPos(1,1)
print("Escaping OS")
sleep(1)
print("Escaped to Command Processor...")
sleep(1)
print("Escape Complete")
print("------------------------------------")
sleep(1)
textutils.slowPrint("To reenter OS execute 'back'.")
print("------------------------------------")