print("-----ServerOs Installer-----")
print("Auto Installation Commencing")
print("----------------------------")
textutils.slowPrint("Wiping OS...")
fs.delete("startup.lua")
fs.delete(".menu.lua")
fs.delete("os")
fs.delete("back.lua")
print("----------------------------")
sleep(1)
textutils.slowPrint("Installing New Files...")
fs.copy("disk/install_media/.menu.lua", "/.menu.lua")
fs.copy("disk/install_media/back.lua", "/back.lua")
fs.copy("disk/install_media/startup.lua", "/startup.lua")
fs.copy("disk/install_media/os/", "/os/")
print("----------------------------")
sleep(1)
--disk.eject("top")
--disk.eject("left")
--disk.eject("right")
--disk.eject("front")
--disk.eject("back")
--disk.eject("bottom")
textutils.slowPrint("ServerOs Installed")
textutils.slowPrint("Rebooting...")
sleep(1)
os.reboot()